
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'ProsePre': typeof import("../../app/components/content/ProsePre.vue")['default']
  'AboutMe': typeof import("../../app/components/AboutMe.vue")['default']
  'AppFooter': typeof import("../../app/components/AppFooter.vue")['default']
  'AppHeader': typeof import("../../app/components/AppHeader.vue")['default']
  'BlogCard': typeof import("../../app/components/Blog/BlogCard.vue")['default']
  'BlogSearchModal': typeof import("../../app/components/Blog/SearchModal.client.vue")['default']
  'BlogSlugHeader': typeof import("../../app/components/Blog/SlugHeader.vue")['default']
  'BookmarkFallback': typeof import("../../app/components/Bookmark/Fallback.vue")['default']
  'BookmarkItem': typeof import("../../app/components/Bookmark/Item.vue")['default']
  'ColorThief': typeof import("../../app/components/ColorThief.vue")['default']
  'FeaturedWork': typeof import("../../app/components/FeaturedWork.vue")['default']
  'FullBleedBorder': typeof import("../../app/components/FullBleedBorder.vue")['default']
  'LatestBlogs': typeof import("../../app/components/LatestBlogs.vue")['default']
  'MainFooter': typeof import("../../app/components/MainFooter.vue")['default']
  'MainNavbar': typeof import("../../app/components/MainNavbar.vue")['default']
  'MotionSlideBlur': typeof import("../../app/components/Motion/SlideBlur.vue")['default']
  'NavbarLangSwitch': typeof import("../../app/components/Navbar/LangSwitch.vue")['default']
  'NavbarMobileNav': typeof import("../../app/components/Navbar/MobileNav.vue")['default']
  'NavbarThemeSwitch': typeof import("../../app/components/Navbar/ThemeSwitch.vue")['default']
  'PageHeader': typeof import("../../app/components/PageHeader.vue")['default']
  'SocialLinks': typeof import("../../app/components/SocialLinks.vue")['default']
  'Technology': typeof import("../../app/components/Technology.vue")['default']
  'TechnologyGridItems': typeof import("../../app/components/Technology/GridItems.vue")['default']
  'WhatIsInMyBagItemContainer': typeof import("../../app/components/WhatIsInMyBag/ItemContainer.vue")['default']
  'UAccordionDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.d.vue")['default']
  'UAccordion': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue")['default']
  'UAlertDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.d.vue")['default']
  'UAlert': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue")['default']
  'UAppDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.d.vue")['default']
  'UApp': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue")['default']
  'UAvatarDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.d.vue")['default']
  'UAvatar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue")['default']
  'UAvatarGroupDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.d.vue")['default']
  'UAvatarGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue")['default']
  'UBadgeDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.d.vue")['default']
  'UBadge': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue")['default']
  'UBreadcrumbDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.d.vue")['default']
  'UBreadcrumb': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue")['default']
  'UButtonDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.d.vue")['default']
  'UButton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue")['default']
  'UButtonGroupDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.d.vue")['default']
  'UButtonGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.vue")['default']
  'UCalendarDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.d.vue")['default']
  'UCalendar': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue")['default']
  'UCardDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.d.vue")['default']
  'UCard': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue")['default']
  'UCarouselDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.d.vue")['default']
  'UCarousel': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue")['default']
  'UCheckboxDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.d.vue")['default']
  'UCheckbox': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue")['default']
  'UCheckboxGroupDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.d.vue")['default']
  'UCheckboxGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue")['default']
  'UChipDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.d.vue")['default']
  'UChip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue")['default']
  'UCollapsibleDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.d.vue")['default']
  'UCollapsible': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue")['default']
  'UColorPickerDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.d.vue")['default']
  'UColorPicker': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue")['default']
  'UCommandPaletteDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.d.vue")['default']
  'UCommandPalette': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue")['default']
  'UContainerDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.d.vue")['default']
  'UContainer': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue")['default']
  'UContextMenuDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.d.vue")['default']
  'UContextMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue")['default']
  'UContextMenuContentDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.d.vue")['default']
  'UContextMenuContent': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue")['default']
  'UDrawerDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.d.vue")['default']
  'UDrawer': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue")['default']
  'UDropdownMenuDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.d.vue")['default']
  'UDropdownMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue")['default']
  'UDropdownMenuContentDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.d.vue")['default']
  'UDropdownMenuContent': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue")['default']
  'UFileUploadDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.d.vue")['default']
  'UFileUpload': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue")['default']
  'UFormDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.d.vue")['default']
  'UForm': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue")['default']
  'UFormFieldDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.d.vue")['default']
  'UFormField': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue")['default']
  'UIconDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.d.vue")['default']
  'UIcon': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue")['default']
  'UInputDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.d.vue")['default']
  'UInput': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue")['default']
  'UInputMenuDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.d.vue")['default']
  'UInputMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue")['default']
  'UInputNumberDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.d.vue")['default']
  'UInputNumber': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue")['default']
  'UInputTagsDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.d.vue")['default']
  'UInputTags': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue")['default']
  'UKbdDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.d.vue")['default']
  'UKbd': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue")['default']
  'ULinkDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.d.vue")['default']
  'ULink': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue")['default']
  'ULinkBaseDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.d.vue")['default']
  'ULinkBase': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue")['default']
  'UModalDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.d.vue")['default']
  'UModal': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue")['default']
  'UNavigationMenuDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.d.vue")['default']
  'UNavigationMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue")['default']
  'UOverlayProviderDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.d.vue")['default']
  'UOverlayProvider': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue")['default']
  'UPaginationDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.d.vue")['default']
  'UPagination': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue")['default']
  'UPinInputDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.d.vue")['default']
  'UPinInput': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue")['default']
  'UPopoverDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.d.vue")['default']
  'UPopover': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue")['default']
  'UProgressDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.d.vue")['default']
  'UProgress': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue")['default']
  'URadioGroupDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.d.vue")['default']
  'URadioGroup': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue")['default']
  'USelectDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.d.vue")['default']
  'USelect': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue")['default']
  'USelectMenuDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.d.vue")['default']
  'USelectMenu': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue")['default']
  'USeparatorDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.d.vue")['default']
  'USeparator': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue")['default']
  'USkeletonDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.d.vue")['default']
  'USkeleton': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue")['default']
  'USlideoverDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.d.vue")['default']
  'USlideover': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue")['default']
  'USliderDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.d.vue")['default']
  'USlider': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue")['default']
  'UStepperDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.d.vue")['default']
  'UStepper': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue")['default']
  'USwitchDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.d.vue")['default']
  'USwitch': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue")['default']
  'UTableDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.d.vue")['default']
  'UTable': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue")['default']
  'UTabsDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.d.vue")['default']
  'UTabs': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue")['default']
  'UTextareaDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.d.vue")['default']
  'UTextarea': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue")['default']
  'UTimelineDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.d.vue")['default']
  'UTimeline': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue")['default']
  'UToastDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.d.vue")['default']
  'UToast': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue")['default']
  'UToasterDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.d.vue")['default']
  'UToaster': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue")['default']
  'UTooltipDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.d.vue")['default']
  'UTooltip': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue")['default']
  'UTreeDVue': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.d.vue")['default']
  'UTree': typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue")['default']
  'ProseA': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
  'ProseBlockquote': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
  'ProseCode': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
  'ProseEm': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
  'ProseH1': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
  'ProseH2': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
  'ProseH3': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
  'ProseH4': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
  'ProseH5': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
  'ProseH6': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
  'ProseHr': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
  'ProseImg': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
  'ProseLi': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
  'ProseOl': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
  'ProseP': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
  'ProseScript': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
  'ProseStrong': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
  'ProseTable': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
  'ProseTbody': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
  'ProseTd': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
  'ProseTh': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
  'ProseThead': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
  'ProseTr': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
  'ProseUl': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
  'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  'NuxtImg': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
  'NuxtPicture': typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
  'Icon': typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
  'ColorScheme': typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
  'NuxtLinkLocale': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
  'SwitchLocalePathLink': typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
  'ContentRenderer': typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
  'MDC': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
  'MDCCached': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']
  'MDCRenderer': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
  'MDCSlot': typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
  'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  'LazyProsePre': LazyComponent<typeof import("../../app/components/content/ProsePre.vue")['default']>
  'LazyAboutMe': LazyComponent<typeof import("../../app/components/AboutMe.vue")['default']>
  'LazyAppFooter': LazyComponent<typeof import("../../app/components/AppFooter.vue")['default']>
  'LazyAppHeader': LazyComponent<typeof import("../../app/components/AppHeader.vue")['default']>
  'LazyBlogCard': LazyComponent<typeof import("../../app/components/Blog/BlogCard.vue")['default']>
  'LazyBlogSearchModal': LazyComponent<typeof import("../../app/components/Blog/SearchModal.client.vue")['default']>
  'LazyBlogSlugHeader': LazyComponent<typeof import("../../app/components/Blog/SlugHeader.vue")['default']>
  'LazyBookmarkFallback': LazyComponent<typeof import("../../app/components/Bookmark/Fallback.vue")['default']>
  'LazyBookmarkItem': LazyComponent<typeof import("../../app/components/Bookmark/Item.vue")['default']>
  'LazyColorThief': LazyComponent<typeof import("../../app/components/ColorThief.vue")['default']>
  'LazyFeaturedWork': LazyComponent<typeof import("../../app/components/FeaturedWork.vue")['default']>
  'LazyFullBleedBorder': LazyComponent<typeof import("../../app/components/FullBleedBorder.vue")['default']>
  'LazyLatestBlogs': LazyComponent<typeof import("../../app/components/LatestBlogs.vue")['default']>
  'LazyMainFooter': LazyComponent<typeof import("../../app/components/MainFooter.vue")['default']>
  'LazyMainNavbar': LazyComponent<typeof import("../../app/components/MainNavbar.vue")['default']>
  'LazyMotionSlideBlur': LazyComponent<typeof import("../../app/components/Motion/SlideBlur.vue")['default']>
  'LazyNavbarLangSwitch': LazyComponent<typeof import("../../app/components/Navbar/LangSwitch.vue")['default']>
  'LazyNavbarMobileNav': LazyComponent<typeof import("../../app/components/Navbar/MobileNav.vue")['default']>
  'LazyNavbarThemeSwitch': LazyComponent<typeof import("../../app/components/Navbar/ThemeSwitch.vue")['default']>
  'LazyPageHeader': LazyComponent<typeof import("../../app/components/PageHeader.vue")['default']>
  'LazySocialLinks': LazyComponent<typeof import("../../app/components/SocialLinks.vue")['default']>
  'LazyTechnology': LazyComponent<typeof import("../../app/components/Technology.vue")['default']>
  'LazyTechnologyGridItems': LazyComponent<typeof import("../../app/components/Technology/GridItems.vue")['default']>
  'LazyWhatIsInMyBagItemContainer': LazyComponent<typeof import("../../app/components/WhatIsInMyBag/ItemContainer.vue")['default']>
  'LazyUAccordionDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.d.vue")['default']>
  'LazyUAccordion': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue")['default']>
  'LazyUAlertDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.d.vue")['default']>
  'LazyUAlert': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue")['default']>
  'LazyUAppDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.d.vue")['default']>
  'LazyUApp': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/App.vue")['default']>
  'LazyUAvatarDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.d.vue")['default']>
  'LazyUAvatar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue")['default']>
  'LazyUAvatarGroupDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.d.vue")['default']>
  'LazyUAvatarGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue")['default']>
  'LazyUBadgeDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.d.vue")['default']>
  'LazyUBadge': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue")['default']>
  'LazyUBreadcrumbDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.d.vue")['default']>
  'LazyUBreadcrumb': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue")['default']>
  'LazyUButtonDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.d.vue")['default']>
  'LazyUButton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue")['default']>
  'LazyUButtonGroupDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.d.vue")['default']>
  'LazyUButtonGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.vue")['default']>
  'LazyUCalendarDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.d.vue")['default']>
  'LazyUCalendar': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue")['default']>
  'LazyUCardDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.d.vue")['default']>
  'LazyUCard': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue")['default']>
  'LazyUCarouselDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.d.vue")['default']>
  'LazyUCarousel': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue")['default']>
  'LazyUCheckboxDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.d.vue")['default']>
  'LazyUCheckbox': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue")['default']>
  'LazyUCheckboxGroupDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.d.vue")['default']>
  'LazyUCheckboxGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue")['default']>
  'LazyUChipDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.d.vue")['default']>
  'LazyUChip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue")['default']>
  'LazyUCollapsibleDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.d.vue")['default']>
  'LazyUCollapsible': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue")['default']>
  'LazyUColorPickerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.d.vue")['default']>
  'LazyUColorPicker': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue")['default']>
  'LazyUCommandPaletteDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.d.vue")['default']>
  'LazyUCommandPalette': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue")['default']>
  'LazyUContainerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.d.vue")['default']>
  'LazyUContainer': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Container.vue")['default']>
  'LazyUContextMenuDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.d.vue")['default']>
  'LazyUContextMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue")['default']>
  'LazyUContextMenuContentDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.d.vue")['default']>
  'LazyUContextMenuContent': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue")['default']>
  'LazyUDrawerDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.d.vue")['default']>
  'LazyUDrawer': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue")['default']>
  'LazyUDropdownMenuDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.d.vue")['default']>
  'LazyUDropdownMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue")['default']>
  'LazyUDropdownMenuContentDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.d.vue")['default']>
  'LazyUDropdownMenuContent': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue")['default']>
  'LazyUFileUploadDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.d.vue")['default']>
  'LazyUFileUpload': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue")['default']>
  'LazyUFormDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.d.vue")['default']>
  'LazyUForm': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue")['default']>
  'LazyUFormFieldDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.d.vue")['default']>
  'LazyUFormField': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue")['default']>
  'LazyUIconDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.d.vue")['default']>
  'LazyUIcon': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue")['default']>
  'LazyUInputDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.d.vue")['default']>
  'LazyUInput': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue")['default']>
  'LazyUInputMenuDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.d.vue")['default']>
  'LazyUInputMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue")['default']>
  'LazyUInputNumberDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.d.vue")['default']>
  'LazyUInputNumber': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue")['default']>
  'LazyUInputTagsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.d.vue")['default']>
  'LazyUInputTags': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue")['default']>
  'LazyUKbdDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.d.vue")['default']>
  'LazyUKbd': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue")['default']>
  'LazyULinkDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.d.vue")['default']>
  'LazyULink': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Link.vue")['default']>
  'LazyULinkBaseDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.d.vue")['default']>
  'LazyULinkBase': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue")['default']>
  'LazyUModalDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.d.vue")['default']>
  'LazyUModal': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue")['default']>
  'LazyUNavigationMenuDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.d.vue")['default']>
  'LazyUNavigationMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue")['default']>
  'LazyUOverlayProviderDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.d.vue")['default']>
  'LazyUOverlayProvider': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue")['default']>
  'LazyUPaginationDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.d.vue")['default']>
  'LazyUPagination': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue")['default']>
  'LazyUPinInputDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.d.vue")['default']>
  'LazyUPinInput': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue")['default']>
  'LazyUPopoverDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.d.vue")['default']>
  'LazyUPopover': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue")['default']>
  'LazyUProgressDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.d.vue")['default']>
  'LazyUProgress': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue")['default']>
  'LazyURadioGroupDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.d.vue")['default']>
  'LazyURadioGroup': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue")['default']>
  'LazyUSelectDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.d.vue")['default']>
  'LazyUSelect': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Select.vue")['default']>
  'LazyUSelectMenuDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.d.vue")['default']>
  'LazyUSelectMenu': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue")['default']>
  'LazyUSeparatorDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.d.vue")['default']>
  'LazyUSeparator': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue")['default']>
  'LazyUSkeletonDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.d.vue")['default']>
  'LazyUSkeleton': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue")['default']>
  'LazyUSlideoverDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.d.vue")['default']>
  'LazyUSlideover': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue")['default']>
  'LazyUSliderDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.d.vue")['default']>
  'LazyUSlider': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue")['default']>
  'LazyUStepperDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.d.vue")['default']>
  'LazyUStepper': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue")['default']>
  'LazyUSwitchDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.d.vue")['default']>
  'LazyUSwitch': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue")['default']>
  'LazyUTableDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.d.vue")['default']>
  'LazyUTable': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Table.vue")['default']>
  'LazyUTabsDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.d.vue")['default']>
  'LazyUTabs': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue")['default']>
  'LazyUTextareaDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.d.vue")['default']>
  'LazyUTextarea': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue")['default']>
  'LazyUTimelineDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.d.vue")['default']>
  'LazyUTimeline': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue")['default']>
  'LazyUToastDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.d.vue")['default']>
  'LazyUToast': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue")['default']>
  'LazyUToasterDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.d.vue")['default']>
  'LazyUToaster': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue")['default']>
  'LazyUTooltipDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.d.vue")['default']>
  'LazyUTooltip': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue")['default']>
  'LazyUTreeDVue': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.d.vue")['default']>
  'LazyUTree': LazyComponent<typeof import("../../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue")['default']>
  'LazyProseA': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
  'LazyProseBlockquote': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
  'LazyProseCode': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']>
  'LazyProseEm': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
  'LazyProseH1': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']>
  'LazyProseH2': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']>
  'LazyProseH3': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']>
  'LazyProseH4': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']>
  'LazyProseH5': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
  'LazyProseH6': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
  'LazyProseHr': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
  'LazyProseImg': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
  'LazyProseLi': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
  'LazyProseOl': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
  'LazyProseP': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
  'LazyProseScript': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
  'LazyProseStrong': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
  'LazyProseTable': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
  'LazyProseTbody': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
  'LazyProseTd': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
  'LazyProseTh': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
  'LazyProseThead': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
  'LazyProseTr': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
  'LazyProseUl': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
  'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
  'LazyIcon': LazyComponent<typeof import("../../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
  'LazyColorScheme': LazyComponent<typeof import("../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
  'LazyNuxtLinkLocale': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
  'LazySwitchLocalePathLink': LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
  'LazyContentRenderer': LazyComponent<typeof import("../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
  'LazyMDC': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
  'LazyMDCCached': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']>
  'LazyMDCRenderer': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
  'LazyMDCSlot': LazyComponent<typeof import("../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
  'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
