
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const ProsePre: typeof import("../app/components/content/ProsePre.vue")['default']
export const AboutMe: typeof import("../app/components/AboutMe.vue")['default']
export const AppFooter: typeof import("../app/components/AppFooter.vue")['default']
export const AppHeader: typeof import("../app/components/AppHeader.vue")['default']
export const BlogCard: typeof import("../app/components/Blog/BlogCard.vue")['default']
export const BlogSearchModal: typeof import("../app/components/Blog/SearchModal.client.vue")['default']
export const BlogSlugHeader: typeof import("../app/components/Blog/SlugHeader.vue")['default']
export const BookmarkFallback: typeof import("../app/components/Bookmark/Fallback.vue")['default']
export const BookmarkItem: typeof import("../app/components/Bookmark/Item.vue")['default']
export const ColorThief: typeof import("../app/components/ColorThief.vue")['default']
export const FeaturedWork: typeof import("../app/components/FeaturedWork.vue")['default']
export const FullBleedBorder: typeof import("../app/components/FullBleedBorder.vue")['default']
export const LatestBlogs: typeof import("../app/components/LatestBlogs.vue")['default']
export const MainFooter: typeof import("../app/components/MainFooter.vue")['default']
export const MainNavbar: typeof import("../app/components/MainNavbar.vue")['default']
export const MotionSlideBlur: typeof import("../app/components/Motion/SlideBlur.vue")['default']
export const NavbarLangSwitch: typeof import("../app/components/Navbar/LangSwitch.vue")['default']
export const NavbarMobileNav: typeof import("../app/components/Navbar/MobileNav.vue")['default']
export const NavbarThemeSwitch: typeof import("../app/components/Navbar/ThemeSwitch.vue")['default']
export const PageHeader: typeof import("../app/components/PageHeader.vue")['default']
export const SocialLinks: typeof import("../app/components/SocialLinks.vue")['default']
export const Technology: typeof import("../app/components/Technology.vue")['default']
export const TechnologyGridItems: typeof import("../app/components/Technology/GridItems.vue")['default']
export const WhatIsInMyBagItemContainer: typeof import("../app/components/WhatIsInMyBag/ItemContainer.vue")['default']
export const UAccordionDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Accordion.d.vue")['default']
export const UAccordion: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue")['default']
export const UAlertDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Alert.d.vue")['default']
export const UAlert: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue")['default']
export const UAppDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/App.d.vue")['default']
export const UApp: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/App.vue")['default']
export const UAvatarDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Avatar.d.vue")['default']
export const UAvatar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue")['default']
export const UAvatarGroupDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.d.vue")['default']
export const UAvatarGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue")['default']
export const UBadgeDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Badge.d.vue")['default']
export const UBadge: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue")['default']
export const UBreadcrumbDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.d.vue")['default']
export const UBreadcrumb: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue")['default']
export const UButtonDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Button.d.vue")['default']
export const UButton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Button.vue")['default']
export const UButtonGroupDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.d.vue")['default']
export const UButtonGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.vue")['default']
export const UCalendarDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Calendar.d.vue")['default']
export const UCalendar: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue")['default']
export const UCardDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Card.d.vue")['default']
export const UCard: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Card.vue")['default']
export const UCarouselDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Carousel.d.vue")['default']
export const UCarousel: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue")['default']
export const UCheckboxDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.d.vue")['default']
export const UCheckbox: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue")['default']
export const UCheckboxGroupDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.d.vue")['default']
export const UCheckboxGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue")['default']
export const UChipDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Chip.d.vue")['default']
export const UChip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue")['default']
export const UCollapsibleDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.d.vue")['default']
export const UCollapsible: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue")['default']
export const UColorPickerDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.d.vue")['default']
export const UColorPicker: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue")['default']
export const UCommandPaletteDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.d.vue")['default']
export const UCommandPalette: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue")['default']
export const UContainerDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Container.d.vue")['default']
export const UContainer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Container.vue")['default']
export const UContextMenuDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.d.vue")['default']
export const UContextMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue")['default']
export const UContextMenuContentDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.d.vue")['default']
export const UContextMenuContent: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue")['default']
export const UDrawerDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Drawer.d.vue")['default']
export const UDrawer: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue")['default']
export const UDropdownMenuDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.d.vue")['default']
export const UDropdownMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue")['default']
export const UDropdownMenuContentDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.d.vue")['default']
export const UDropdownMenuContent: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue")['default']
export const UFileUploadDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.d.vue")['default']
export const UFileUpload: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue")['default']
export const UFormDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Form.d.vue")['default']
export const UForm: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Form.vue")['default']
export const UFormFieldDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FormField.d.vue")['default']
export const UFormField: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue")['default']
export const UIconDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Icon.d.vue")['default']
export const UIcon: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue")['default']
export const UInputDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Input.d.vue")['default']
export const UInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Input.vue")['default']
export const UInputMenuDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.d.vue")['default']
export const UInputMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue")['default']
export const UInputNumberDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.d.vue")['default']
export const UInputNumber: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue")['default']
export const UInputTagsDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputTags.d.vue")['default']
export const UInputTags: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue")['default']
export const UKbdDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Kbd.d.vue")['default']
export const UKbd: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue")['default']
export const ULinkDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Link.d.vue")['default']
export const ULink: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Link.vue")['default']
export const ULinkBaseDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.d.vue")['default']
export const ULinkBase: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue")['default']
export const UModalDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Modal.d.vue")['default']
export const UModal: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue")['default']
export const UNavigationMenuDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.d.vue")['default']
export const UNavigationMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue")['default']
export const UOverlayProviderDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.d.vue")['default']
export const UOverlayProvider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue")['default']
export const UPaginationDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Pagination.d.vue")['default']
export const UPagination: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue")['default']
export const UPinInputDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PinInput.d.vue")['default']
export const UPinInput: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue")['default']
export const UPopoverDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Popover.d.vue")['default']
export const UPopover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue")['default']
export const UProgressDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Progress.d.vue")['default']
export const UProgress: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue")['default']
export const URadioGroupDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.d.vue")['default']
export const URadioGroup: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue")['default']
export const USelectDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Select.d.vue")['default']
export const USelect: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Select.vue")['default']
export const USelectMenuDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.d.vue")['default']
export const USelectMenu: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue")['default']
export const USeparatorDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Separator.d.vue")['default']
export const USeparator: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue")['default']
export const USkeletonDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.d.vue")['default']
export const USkeleton: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue")['default']
export const USlideoverDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slideover.d.vue")['default']
export const USlideover: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue")['default']
export const USliderDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slider.d.vue")['default']
export const USlider: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue")['default']
export const UStepperDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Stepper.d.vue")['default']
export const UStepper: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue")['default']
export const USwitchDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Switch.d.vue")['default']
export const USwitch: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue")['default']
export const UTableDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Table.d.vue")['default']
export const UTable: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Table.vue")['default']
export const UTabsDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tabs.d.vue")['default']
export const UTabs: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue")['default']
export const UTextareaDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Textarea.d.vue")['default']
export const UTextarea: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue")['default']
export const UTimelineDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Timeline.d.vue")['default']
export const UTimeline: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue")['default']
export const UToastDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toast.d.vue")['default']
export const UToast: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue")['default']
export const UToasterDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toaster.d.vue")['default']
export const UToaster: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue")['default']
export const UTooltipDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.d.vue")['default']
export const UTooltip: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue")['default']
export const UTreeDVue: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tree.d.vue")['default']
export const UTree: typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue")['default']
export const ProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseCode: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']
export const ProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const NuxtLinkLocale: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
export const SwitchLocalePathLink: typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
export const ContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const MDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCCached: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']
export const MDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyProsePre: LazyComponent<typeof import("../app/components/content/ProsePre.vue")['default']>
export const LazyAboutMe: LazyComponent<typeof import("../app/components/AboutMe.vue")['default']>
export const LazyAppFooter: LazyComponent<typeof import("../app/components/AppFooter.vue")['default']>
export const LazyAppHeader: LazyComponent<typeof import("../app/components/AppHeader.vue")['default']>
export const LazyBlogCard: LazyComponent<typeof import("../app/components/Blog/BlogCard.vue")['default']>
export const LazyBlogSearchModal: LazyComponent<typeof import("../app/components/Blog/SearchModal.client.vue")['default']>
export const LazyBlogSlugHeader: LazyComponent<typeof import("../app/components/Blog/SlugHeader.vue")['default']>
export const LazyBookmarkFallback: LazyComponent<typeof import("../app/components/Bookmark/Fallback.vue")['default']>
export const LazyBookmarkItem: LazyComponent<typeof import("../app/components/Bookmark/Item.vue")['default']>
export const LazyColorThief: LazyComponent<typeof import("../app/components/ColorThief.vue")['default']>
export const LazyFeaturedWork: LazyComponent<typeof import("../app/components/FeaturedWork.vue")['default']>
export const LazyFullBleedBorder: LazyComponent<typeof import("../app/components/FullBleedBorder.vue")['default']>
export const LazyLatestBlogs: LazyComponent<typeof import("../app/components/LatestBlogs.vue")['default']>
export const LazyMainFooter: LazyComponent<typeof import("../app/components/MainFooter.vue")['default']>
export const LazyMainNavbar: LazyComponent<typeof import("../app/components/MainNavbar.vue")['default']>
export const LazyMotionSlideBlur: LazyComponent<typeof import("../app/components/Motion/SlideBlur.vue")['default']>
export const LazyNavbarLangSwitch: LazyComponent<typeof import("../app/components/Navbar/LangSwitch.vue")['default']>
export const LazyNavbarMobileNav: LazyComponent<typeof import("../app/components/Navbar/MobileNav.vue")['default']>
export const LazyNavbarThemeSwitch: LazyComponent<typeof import("../app/components/Navbar/ThemeSwitch.vue")['default']>
export const LazyPageHeader: LazyComponent<typeof import("../app/components/PageHeader.vue")['default']>
export const LazySocialLinks: LazyComponent<typeof import("../app/components/SocialLinks.vue")['default']>
export const LazyTechnology: LazyComponent<typeof import("../app/components/Technology.vue")['default']>
export const LazyTechnologyGridItems: LazyComponent<typeof import("../app/components/Technology/GridItems.vue")['default']>
export const LazyWhatIsInMyBagItemContainer: LazyComponent<typeof import("../app/components/WhatIsInMyBag/ItemContainer.vue")['default']>
export const LazyUAccordionDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Accordion.d.vue")['default']>
export const LazyUAccordion: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue")['default']>
export const LazyUAlertDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Alert.d.vue")['default']>
export const LazyUAlert: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Alert.vue")['default']>
export const LazyUAppDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/App.d.vue")['default']>
export const LazyUApp: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/App.vue")['default']>
export const LazyUAvatarDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Avatar.d.vue")['default']>
export const LazyUAvatar: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue")['default']>
export const LazyUAvatarGroupDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.d.vue")['default']>
export const LazyUAvatarGroup: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/AvatarGroup.vue")['default']>
export const LazyUBadgeDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Badge.d.vue")['default']>
export const LazyUBadge: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue")['default']>
export const LazyUBreadcrumbDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.d.vue")['default']>
export const LazyUBreadcrumb: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue")['default']>
export const LazyUButtonDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Button.d.vue")['default']>
export const LazyUButton: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Button.vue")['default']>
export const LazyUButtonGroupDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.d.vue")['default']>
export const LazyUButtonGroup: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.vue")['default']>
export const LazyUCalendarDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Calendar.d.vue")['default']>
export const LazyUCalendar: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue")['default']>
export const LazyUCardDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Card.d.vue")['default']>
export const LazyUCard: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Card.vue")['default']>
export const LazyUCarouselDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Carousel.d.vue")['default']>
export const LazyUCarousel: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue")['default']>
export const LazyUCheckboxDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.d.vue")['default']>
export const LazyUCheckbox: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue")['default']>
export const LazyUCheckboxGroupDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.d.vue")['default']>
export const LazyUCheckboxGroup: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CheckboxGroup.vue")['default']>
export const LazyUChipDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Chip.d.vue")['default']>
export const LazyUChip: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Chip.vue")['default']>
export const LazyUCollapsibleDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.d.vue")['default']>
export const LazyUCollapsible: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue")['default']>
export const LazyUColorPickerDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.d.vue")['default']>
export const LazyUColorPicker: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ColorPicker.vue")['default']>
export const LazyUCommandPaletteDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.d.vue")['default']>
export const LazyUCommandPalette: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/CommandPalette.vue")['default']>
export const LazyUContainerDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Container.d.vue")['default']>
export const LazyUContainer: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Container.vue")['default']>
export const LazyUContextMenuDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.d.vue")['default']>
export const LazyUContextMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue")['default']>
export const LazyUContextMenuContentDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.d.vue")['default']>
export const LazyUContextMenuContent: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/ContextMenuContent.vue")['default']>
export const LazyUDrawerDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Drawer.d.vue")['default']>
export const LazyUDrawer: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Drawer.vue")['default']>
export const LazyUDropdownMenuDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.d.vue")['default']>
export const LazyUDropdownMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue")['default']>
export const LazyUDropdownMenuContentDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.d.vue")['default']>
export const LazyUDropdownMenuContent: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/DropdownMenuContent.vue")['default']>
export const LazyUFileUploadDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.d.vue")['default']>
export const LazyUFileUpload: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FileUpload.vue")['default']>
export const LazyUFormDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Form.d.vue")['default']>
export const LazyUForm: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Form.vue")['default']>
export const LazyUFormFieldDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FormField.d.vue")['default']>
export const LazyUFormField: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue")['default']>
export const LazyUIconDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Icon.d.vue")['default']>
export const LazyUIcon: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Icon.vue")['default']>
export const LazyUInputDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Input.d.vue")['default']>
export const LazyUInput: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Input.vue")['default']>
export const LazyUInputMenuDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.d.vue")['default']>
export const LazyUInputMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputMenu.vue")['default']>
export const LazyUInputNumberDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.d.vue")['default']>
export const LazyUInputNumber: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputNumber.vue")['default']>
export const LazyUInputTagsDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputTags.d.vue")['default']>
export const LazyUInputTags: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/InputTags.vue")['default']>
export const LazyUKbdDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Kbd.d.vue")['default']>
export const LazyUKbd: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue")['default']>
export const LazyULinkDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Link.d.vue")['default']>
export const LazyULink: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Link.vue")['default']>
export const LazyULinkBaseDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.d.vue")['default']>
export const LazyULinkBase: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue")['default']>
export const LazyUModalDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Modal.d.vue")['default']>
export const LazyUModal: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue")['default']>
export const LazyUNavigationMenuDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.d.vue")['default']>
export const LazyUNavigationMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue")['default']>
export const LazyUOverlayProviderDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.d.vue")['default']>
export const LazyUOverlayProvider: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/OverlayProvider.vue")['default']>
export const LazyUPaginationDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Pagination.d.vue")['default']>
export const LazyUPagination: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue")['default']>
export const LazyUPinInputDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PinInput.d.vue")['default']>
export const LazyUPinInput: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/PinInput.vue")['default']>
export const LazyUPopoverDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Popover.d.vue")['default']>
export const LazyUPopover: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Popover.vue")['default']>
export const LazyUProgressDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Progress.d.vue")['default']>
export const LazyUProgress: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Progress.vue")['default']>
export const LazyURadioGroupDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.d.vue")['default']>
export const LazyURadioGroup: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/RadioGroup.vue")['default']>
export const LazyUSelectDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Select.d.vue")['default']>
export const LazyUSelect: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Select.vue")['default']>
export const LazyUSelectMenuDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.d.vue")['default']>
export const LazyUSelectMenu: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue")['default']>
export const LazyUSeparatorDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Separator.d.vue")['default']>
export const LazyUSeparator: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue")['default']>
export const LazyUSkeletonDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.d.vue")['default']>
export const LazyUSkeleton: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue")['default']>
export const LazyUSlideoverDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slideover.d.vue")['default']>
export const LazyUSlideover: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue")['default']>
export const LazyUSliderDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slider.d.vue")['default']>
export const LazyUSlider: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Slider.vue")['default']>
export const LazyUStepperDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Stepper.d.vue")['default']>
export const LazyUStepper: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Stepper.vue")['default']>
export const LazyUSwitchDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Switch.d.vue")['default']>
export const LazyUSwitch: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue")['default']>
export const LazyUTableDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Table.d.vue")['default']>
export const LazyUTable: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Table.vue")['default']>
export const LazyUTabsDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tabs.d.vue")['default']>
export const LazyUTabs: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue")['default']>
export const LazyUTextareaDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Textarea.d.vue")['default']>
export const LazyUTextarea: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue")['default']>
export const LazyUTimelineDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Timeline.d.vue")['default']>
export const LazyUTimeline: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue")['default']>
export const LazyUToastDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toast.d.vue")['default']>
export const LazyUToast: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toast.vue")['default']>
export const LazyUToasterDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toaster.d.vue")['default']>
export const LazyUToaster: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Toaster.vue")['default']>
export const LazyUTooltipDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.d.vue")['default']>
export const LazyUTooltip: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue")['default']>
export const LazyUTreeDVue: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tree.d.vue")['default']>
export const LazyUTree: LazyComponent<typeof import("../node_modules/@nuxt/ui/dist/runtime/components/Tree.vue")['default']>
export const LazyProseA: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']>
export const LazyProseBlockquote: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']>
export const LazyProseCode: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseCode.vue")['default']>
export const LazyProseEm: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']>
export const LazyProseH1: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']>
export const LazyProseH2: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']>
export const LazyProseH3: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']>
export const LazyProseH4: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']>
export const LazyProseH5: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']>
export const LazyProseH6: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']>
export const LazyProseHr: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']>
export const LazyProseImg: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']>
export const LazyProseLi: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']>
export const LazyProseOl: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']>
export const LazyProseP: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']>
export const LazyProseScript: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']>
export const LazyProseStrong: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']>
export const LazyProseTable: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']>
export const LazyProseTbody: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']>
export const LazyProseTd: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']>
export const LazyProseTh: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']>
export const LazyProseThead: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']>
export const LazyProseTr: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']>
export const LazyProseUl: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']>
export const LazyIcon: LazyComponent<typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']>
export const LazyColorScheme: LazyComponent<typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']>
export const LazyNuxtLinkLocale: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
export const LazySwitchLocalePathLink: LazyComponent<typeof import("../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
export const LazyContentRenderer: LazyComponent<typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']>
export const LazyMDC: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']>
export const LazyMDCCached: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCCached.vue")['default']>
export const LazyMDCRenderer: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']>
export const LazyMDCSlot: LazyComponent<typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
